spring.application.name=CodePulse
spring.datasource.url=jdbc:mysql://localhost:3306/codepulse
spring.datasource.username=root
spring.datasource.password=SHalini12@*

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true